# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: 'node install'
  inputs:
    versionSource: 'spec'
    versionSpec:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'QuickApp/ClientApp'
- task: Npm@1
  displayName: 'npm run & build'
  inputs:
    command: 'custom'
    workingDir: 'QuickApp/ClientApp'
    customCommand: 'run build'
- task: DotNetCoreCLI@2
  displayName: '.net restore'
  inputs:
    command: 'restore'
    projects: 'QuickApp.sln'
    feedsToUse: 'select'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net build'
  inputs:
    command: 'build'
    projects: 'QuickApp.sln'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net test'
  inputs:
    command: 'test'
    projects: 'QuickApp.sln'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    configuration: 'Release'
